name: Check

on:
  # Post-submit.
  push:
    branches: [ main ]

  # Pre-submit.
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dart-lang/setup-dart@v1.6.4
      - uses: actions/setup-node@v4
      - uses: browser-actions/setup-chrome@v1
      - run: dart pub get
      - run: dart format --output none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test
      - run: ./chore coverage -- -P coverage
      - name: Upload coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
